server.port=9000
spring.application.name=authserver
logging.level.org.springframework.security=TRACE

spring.datasource.url=jdbc:postgresql://localhost:15432/auth_db?options=-c%20timezone=UTC
spring.datasource.username=root
spring.datasource.password=rootpassword
spring.jpa.hibernate.ddl-auto=update
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
