server.port=8082
spring.application.name=inventoryserver

spring.datasource.url=jdbc:h2:file:./data/inventorydb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# OAuth2 Resource Server - validates JWT Bearer tokens from AuthServer
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://127.0.0.1:9000
